### ISSUE TITLE
Add Support for Postgres in Document Store

### ISSUE THREAD

**Issue by jainnidhi703** [hypertrace/hypertrace#114]
## Use Case
Adding an alternative datastore i.e. Postgres to the document store, currently, it is limited to MongoDB only.

## Proposal
The entity document will be stored as json in Postgres data-store. Following the conventions from MongoDB,
the postgres schema will look as follows:
```sql
CREATE TABLE documents (
	id TEXT PRIMARY KEY,
	document JSONB NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
```
The document-store will connect to Postgres via JDBC driver. 

I'm already working on a PR to add this. Here is the initial draft of the [PR](https://github.com/hypertrace/document-store/pull/9).
All the functionalities provided by MongoDB will be implemeneted on Postgres as well.

**Comment by JBAhire** [comment]
Thanks for initiating this @jainnidhi703 ! looking forward to it! :)

**Comment by kotharironak** [comment]
Closing this as above PR adds support for this.
