### ISSUE TITLE
Upgrade Mongo java driver in document-store

### ISSUE THREAD

**Issue by buchi-busireddy** [hypertrace/hypertrace#120]
## Proposal
Currently we are using `3.12` mongo java driver in the document-store for MongoCollection implementation but we have already upgraded our MongoDB server to `4.4.0`. 
We are running into some issues in bulk upserting the docs via entity-service APIs. Since there were a lot of changes in that area in the recent mongo java driver, it's better we upgrade the java driver to recent versions and see if the bulk upsert issues are solved. 
cc @avinashkolluru

**Comment by kotharironak** [comment]
@buchi-busireddy Can this be closed?

**Comment by buchi-busireddy** [comment]
Yes @kotharironak This is done.
