### ISSUE TITLE
bug in table interaction

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#129]
## Use Case
I deployed Hypertrace with latest charts on EKS and I am using hotrod to application to generate traces. I am observing this weird blue selection while clicking on traces with blank metadata fields. 

<img width="2672" alt="Screenshot 2020-11-24 at 6 59 03 PM" src="https://user-images.githubusercontent.com/26570044/100120370-e44e1e00-2e9d-11eb-91bf-37c9585c8db4.png">

<img width="2672" alt="Screenshot 2020-11-24 at 6 58 33 PM" src="https://user-images.githubusercontent.com/26570044/100120380-e617e180-2e9d-11eb-91f2-8126eb5f177e.png">

<img width="2672" alt="Screenshot 2020-11-24 at 6 54 35 PM" src="https://user-images.githubusercontent.com/26570044/100120385-e7490e80-2e9d-11eb-8a39-8309f3007e14.png">

**Comment by JBAhire** [comment]
This is happening because we are showing multiple traces with same Trace IDs in Traces board. 
<img width="2297" alt="Screenshot 2020-12-16 at 11 27 15 AM" src="https://user-images.githubusercontent.com/26570044/102310847-cbfb8b80-3f91-11eb-89cc-4cd7d045683d.png">

**Comment by jake-bassett** [comment]
@JBAhire, this seems like a data issue. Do you know why there are multiple traces with the same ID?

**Comment by JBAhire** [comment]
This has been resolved with UI changes. Closing this.
