### ISSUE TITLE
Duplicated selection and missing endpoint

### ISSUE THREAD

**Issue by jcchavezs** [hypertrace/hypertrace#140]
## Use Case
When running the [goagent example](https://github.com/jcchavezs/hypertrace-goagent-example) I see strange behaviour on one of the services' traces. I recorded this video to show the problems:

https://www.loom.com/share/67fbc55a48c84b03b87690a5f4833bb0

Ping @kotharironak @JBAhire @rish691

**Comment by JBAhire** [comment]
related: https://github.com/hypertrace/hypertrace/issues/129

**Comment by JBAhire** [comment]
This is resolved in latest helm deployment with UI chart update.

**Comment by jcchavezs** [comment]
Thanks!
