### ISSUE TITLE
Release process for Hypertrace 

### ISSUE THREAD

**Issue by buchi-busireddy** [hypertrace/hypertrace#145]
Logging this issue to come up with the release process for Hypertrace, which includes the docker-compose and helm charts and make the corresponding changes so that users can use a pinned version instead of always forking the repo and using the latest from the main branch. 
Once we have the release process and artifacts, we need to update the documentation also to fetch the latest version and install rather than cloning the repo. 

cc @JBAhire @kotharironak @jcchavezs

**Comment by JBAhire** [comment]
@buchi-busireddy , closing this as we are maintaining versions for this repo now.
