### ISSUE TITLE
Empty url in services screen on HT UI

### ISSUE THREAD

**Issue by asldevi** [hypertrace/hypertrace#150]
Screen: services -> endpoints -> traces 

From graphQL query, I could see that this is request_url in `spanEventView` in Pinot and it's not populated for many spans in that view resulting in UI showing it empty.

```
select count(*) from spanEventView where request_url = 'null' 
365562132
select count(*) from spanEventView where request_url != 'null' 
951625
```

<img width="1438" alt="Screenshot 2021-01-05 at 4 39 53 PM" src="https://user-images.githubusercontent.com/8813/103640299-c46a4980-4f75-11eb-986e-67ad6485e4a9.png">

**Comment by asldevi** [comment]
Basically, here the request url is coming from pinot view {{spanEventView}} and that's null. [Trace enricher generates this based on the protocol](https://github.com/hypertrace/hypertrace-ingester/blob/05a6a27357848463db138aad3a3b493e60913897/hypertrace-view-generator/hypertrace-view-generator/src/main/java/org/hypertrace/viewgenerator/generators/SpanEventViewGenerator.java#L287-L300) which in turn is [generated based on the tags](https://github.com/hypertrace/hypertrace-ingester/blob/a85a77aa2f7754a2ee35aefadfe069b73a187ec1/hypertrace-trace-enricher/hypertrace-trace-enricher-impl/src/main/java/org/hypertrace/traceenricher/enrichment/enrichers/SpanTypeAttributeEnricher.java#L167-L263).

**Comment by JBAhire** [comment]
I tested this and this has been resolved with latest `hypertrace-ingester` charts. 

Related issue: https://github.com/hypertrace/hypertrace-ingester/issues/111
