### ISSUE TITLE
Span id showing up as trace id  in backends

### ISSUE THREAD

**Issue by asldevi** [hypertrace/hypertrace#151]
Screen: Backends (backends/backend/\<backend_id\>/)

<img width="1418" alt="Screenshot 2021-01-05 at 5 05 56 PM 1" src="https://user-images.githubusercontent.com/8813/103642936-e239ad80-4f79-11eb-9227-896a464dcd0f.png">

**Comment by kotharironak** [comment]
@jake-bassett Is this fixed on hypertrace side in the latest `hypertrace-ui` version?
@JBAhire Can we verify this?

**Comment by JBAhire** [comment]
Yes @kotharironak . I have verified and this issue is fixed in latest UI release. Closing this. :)
