### ISSUE TITLE
[Feature Request] - Adding Sorting capabilities on spans and grouping services by count of traces

### ISSUE THREAD

**Issue by venkatvghub** [hypertrace/hypertrace#176]
## Use Case
**UC-1: Count of Spans:** There are some useful features that Jaeger UI provides which we would like to see on HT UI. For instance, one of the biggest issues we caught on production was actually having a count on the number of spans for different traces. For example, look at [this](https://raw.githubusercontent.com/jaegertracing/jaeger-ui/master/media/ss_search.png). If you notice this, it gives me a clear indication around the number spans consumed per backend. In this example, if you look at the first trace of `frontend HTTP GET /dispatch`, you will notice it has 1 span for mysql, 13 spans for redis etc. Such information is extremely useful to identify bottlenecks in the code. For instance, we were able to identify in our case, some blocks of code that was issuing multiple calls to redis, which we figured from our internal jaeger UI and went ahead to fix the same. Today, hypertrace UI doesn't seem to have an option to drill down to this level. 

 **UC-2: Filtering by count:** Another useful feature we got from jaeger UI was around filtering by most number of spans, least number of spans etc. In essence, it has the options:
-  Most Recent
- Longest First (This is around the complete trace latency)
- Shortest First(This is around the complete trace latency)
- Most spans(Based on the count of most spans across the endpoint/tracer)
- Least Spans(Based on the count of most spans across the endpoint/tracer)

Reference screenshot:
![Screenshot 2021-02-02 at 4 03 31 PM](https://user-images.githubusercontent.com/5548660/106588232-8eb68180-6570-11eb-8e02-524676fc7bba.png)

The above helps me again filter out worst routes vs best routes. Yes, filtering by latency is available in the HT UI though, but not sorting by count of spans or by recency

## Proposal
Disclaimer: Am not a UI expert, so please treat the below with utmost grains of all kinds of salts :). 
1. For handling [UC-1: Count of Spans]: I can think of actually think of somehow adding these in the services tab under a specific service+route combination. Again, not the best person to comment how this should appear.
2. For handling [UC-1: Filtering by count] : Again, this can be exposed with support for filtering options on the services tab or in the exploration tab.

**Comment by jcchavezs** [comment]
Thanks @venkatvghub for describing the use cases, definitively both things are desirable for us too.

**Comment by kotharironak** [comment]
@venkatvghub Yes, the use cases on sorting on spans count makes sense.  In the current, service tab, we have options to sorting based on start_time and duration (latency). So, to me, we can have an additional column on the same tab with `span count` information.
<img width="1672" alt="Screenshot 2021-02-10 at 7 30 31 PM" src="https://user-images.githubusercontent.com/53209990/107519943-dd9a9180-6bd6-11eb-9894-66618234a91a.png">

We did some understanding around the work involved to provide that. Here, we will need to enhance the backend for the `API_TRACE` scope with `spans count` information, and changes in UI to populate that data.

cc: @arjunlalb

**Comment by kotharironak** [comment]
cc @pavolloffay

**Comment by aaron-steinfeld** [comment]
I agree with the use case, and it isn't difficult to implement. The part I'd want to probe into is API Traces vs (Distributed Traces). This screen shows API Traces (very confusingly IMO) - which is a fragment of a trace starting from the entity of interest. Would we expect that span count to reflect the span count of the API trace, or the full distributed trace to which it belongs?

**Comment by kotharironak** [comment]
Here, I was thinking, it will reflect the span count of the API trace as this is the API trace view. Currently, we don't have a screen for distributed traces explicitly which I think is quite useful for analysis. 

Option 1: Add it in explore along with spans 
<img width="1672" alt="Screenshot 2021-02-11 at 2 37 13 PM" src="https://user-images.githubusercontent.com/53209990/107619949-f4de8b00-6c79-11eb-9381-27bd327c2307.png">

Option 2: Introduce one more tab in the services block for Distributed Traces, this will show all distributed traces (full trace) in which this service was involved.
<img width="1674" alt="Screenshot 2021-02-11 at 2 55 21 PM" src="https://user-images.githubusercontent.com/53209990/107620044-18093a80-6c7a-11eb-9d18-03f4b153c1bd.png">

**Comment by aaron-steinfeld** [comment]
Yeah, we've gone back and forth on whether to surface both, but I tend to agree. For now, the distributed trace is available via a link from the api trace. If we do that, I'd consider it a separate issue though. For the existing screen, adding span count is feasible if we start populating that data - the only catch there is that an api trace is not its own object today, it's just a head span. We could always throw more data on it regarding its status as the head span of an api trace, but that's a slippery slope.

**Comment by kotharironak** [comment]
As discussed [here](https://github.com/hypertrace/hypertrace-ingester/pull/130#issuecomment-781182851), in the given context of API Trace, span_count will be an inconsistent metric, so, we will go ahead with a number of immediate downstream call as metrics.

`direct_api_calls`: The total number of outgoing calls to any of the immediate downstream service's API from the current endpoint. Internally it reefers to exit calls to downstream services.

**Comment by asldevi** [comment]
@kotharironak 
1. is the plan to show total span_count in the raw trace view? 
2. Would we be able to see number of backend calls per backend as part of `direct_api_calls`? this will be particularly useful to see how many db/redis requests are made in this route. 

For example, If a route `xyz` is making 3 db calls in a row, what would `direct_api_calls` show? `myapp_database(3) or myapp_database(1)`?
