### ISSUE TITLE
Update default branch name

### ISSUE THREAD

**Issue by adriancole** [hypertrace/hypertrace#18]
As it seems we'd historically made a decision to rename default branches, this issue can track them so that anything hanging off it can be addressed, such as corresponding docker tags representing last commit.

- [x] https://github.com/hypertrace/attribute-service
- [x] https://github.com/hypertrace/blog
- [x] https://github.com/hypertrace/config-bootstrapper
- [x] https://github.com/hypertrace/data-model
- [x] https://github.com/hypertrace/docker-java-base
- [x] https://github.com/hypertrace/document-store
- [x] https://github.com/hypertrace/entity-service
- [x] https://github.com/hypertrace/event-store
- [x] https://github.com/hypertrace/flink-utils
- [x] https://github.com/hypertrace/gateway-service
- [x] https://github.com/hypertrace/helm-gcs-packager
- [x] https://github.com/hypertrace/hyperdash
- [x] https://github.com/hypertrace/hyperdash-angular
- [x] https://github.com/hypertrace/hypertrace
- [x] https://github.com/hypertrace/hypertrace-core-graphql
- [x] https://github.com/hypertrace/hypertrace-core-ui
- [x] https://github.com/hypertrace/hypertrace-core-view-generator
- [x] https://github.com/hypertrace/hypertrace-federated-service
- [x] https://github.com/hypertrace/hypertrace-gradle-avro-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-ci-utils-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-docker-plugins
- [x] https://github.com/hypertrace/hypertrace-gradle-integration-test-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-jacoco-report-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-publish-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-repository-plugin
- [x] https://github.com/hypertrace/hypertrace-gradle-version-settings-plugin
- [x] https://github.com/hypertrace/hypertrace-graphql
- [x] https://github.com/hypertrace/hypertrace-samples
- [x] https://github.com/hypertrace/hypertrace-trace-enricher
- [x] https://github.com/hypertrace/hypertrace-ui
- [x] https://github.com/hypertrace/hypertrace-view-generator
- [x] https://github.com/hypertrace/java-grpc-utils
- [x] https://github.com/hypertrace/kafka
- [x] https://github.com/hypertrace/kafka-topic-creator
- [x] https://github.com/hypertrace/mongodb
- [x] https://github.com/hypertrace/opencensus-service
- [x] https://github.com/hypertrace/opentelemetry-collector
- [x] https://github.com/hypertrace/pinot
- [x] https://github.com/hypertrace/query-service
- [x] https://github.com/hypertrace/raw-spans-grouper
- [x] https://github.com/hypertrace/schema-registry
- [x] https://github.com/hypertrace/service-framework
- [x] https://github.com/hypertrace/span-normalizer
- [x] https://github.com/hypertrace/view-generator-framework
- [x] https://github.com/hypertrace/zookeeper

**Comment by aaron-steinfeld** [comment]
So two questions to resolve here before proceeding.
### The fun one: what branch name to use?
I think with the major VCS hosts moving the project defaults, projects will follow.
- GitHub - migrating from `master` to `main` as default, but making the default configurable (https://github.com/github/renaming )
- GitLab - https://gitlab.com/gitlab-org/gitlab/-/issues/221164#proposal (also settled on `main` as default, good discussion of options/rationale here)
- BitBucket - 🤷  basically following git and making default configurable, not committing to a specific replacement https://jira.atlassian.com/browse/BCLOUD-20212

All of the indications I see indicate to me that `main` has the most traction by far, even if not widely adopted yet.

### Timing?
GH recommends waiting on their tooling ( https://github.com/github/renaming#now-supporting-early-movers- ), but realistically, the level of effort given the amount of traffic on our repos isn’t significantly different - I believe it's just step 3 below. I'd personally rather just get it over with now, but don't have super strong opinions if people disagree.

### Actual work required per repo
1. Merge PR updating circleci config replacing any branch filters (target this at master, which means a publish won't run on merge - that's fine)
2. GH admin: update default branch
3. GH admin: retarget branch protection rules to new default branch, existing PRs at new default branch

**Comment by aaron-steinfeld** [comment]
Will be proceeding with this change over the next couple days, using the branch name `main`. Last call if anyone has any concerns.

**Comment by adriancole** [comment]
FWIW I was thinking about trunk, dev, etc used in practice prior to the recent renaming of things. However, this is a new project (1 month old) if we had done this a month later it would be main. so might as well do main!

**Comment by aaron-steinfeld** [comment]
All repos have been updated.

**Comment by adriancole** [comment]
thanks! we probably need for posterity to suggest commands to update your existing clone (or a link that says the same) unless the idea is to have people re-clone

**Comment by adriancole** [comment]
There are a ton of links like this, but here's what to do from https://www.git-tower.com/learn/git/faq/git-rename-master-to-main

```
# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main
```

**Comment by aaron-steinfeld** [comment]
Nothing should need to be done for your existing clone, although it depends on your workflow. If you're viewing the master branch on your local, you can `git fetch && git checkout main`. If you have an in flight branch you can `git rebase origin/main` or `git merge origin/main` (the same as you would with a master update, except now it's called main)

**Comment by aaron-steinfeld** [comment]
So those are commands to actually repurpose your exist master branch to call it main. No real reason to do that (unless you have some local modification on it, but that should be on a separate branch generally), instead just toss it and checkout main which means you don't have to rename, unset/reset upstream.

**Comment by aaron-steinfeld** [comment]
That ticket above is the submodule equivalent of being on master and trying to pull it after switching to main. If you had existing submodules checked out locally, your local copies were tracking something - the default branch, if not configured otherwise. An explicit update (i.e. `git fetch && git checkout main`) would still work, same as a regular repo. So the above change is fine, but not necessary as it just supports being able to do a no-reference update for an existing repo.

**Comment by adriancole** [comment]
@kotharironak ^^ in case you aren't watching this ticket. some advice might be helpful for next time.
