### ISSUE TITLE
Update docker-plugins to apply new release policy

### ISSUE THREAD

**Issue by adriancole** [hypertrace/hypertrace#19]
Following this change, the subsequent version of `org.hypertrace.docker-publish-plugin` and associated others (like `docker-java-application-plugin`) should be updated to ensure that merging a pull request updates the "last commit" tag, but does not update the "latest" tag or create a new version.

https://github.com/hypertrace/hypertrace-gradle-docker-plugins/pull/14

- [x] https://github.com/hypertrace/attribute-service [PR]
- [x] https://github.com/hypertrace/config-bootstrapper [PR]
- [ ] https://github.com/hypertrace/docker-java-base [PR](https://github.com/hypertrace/docker-java-base/pull/2)
- [x] https://github.com/hypertrace/entity-service [PR]
- [x] https://github.com/hypertrace/gateway-service [PR]
- [ ] https://github.com/hypertrace/helm-gcs-packager
- [ ] https://github.com/hypertrace/hypertrace-core-graphql
- [ ] https://github.com/hypertrace/hypertrace-core-ui
- [x] https://github.com/hypertrace/hypertrace-service
- [x] https://github.com/hypertrace/hypertrace-graphql
- [x] https://github.com/hypertrace/hypertrace-ui
- [x] https://github.com/hypertrace/kafka
- [x] https://github.com/hypertrace/mongodb
- [x] https://github.com/hypertrace/opencensus-service
- [x] https://github.com/hypertrace/pinot
- [x] https://github.com/hypertrace/query-service [PR]
- [x] https://github.com/hypertrace/schema-registry
- [x] https://github.com/hypertrace/hypertrace-ingester
- [x] https://github.com/hypertrace/zookeeper [PR](https://github.com/hypertrace/zookeeper/pull/4)

**Comment by adriancole** [comment]
ttps://github.com/hypertrace/hypertrace-gradle-docker-plugins/pull/14 is now merged, so will update pending PRs to weave it in

**Comment by adriancole** [comment]
@aaron-steinfeld so https://app.circleci.com/pipelines/github/hypertrace/helm-gcs-packager I think we should release 0.2.0 and this is good practice anyway. What's the process to do that? Do we push a git tag 0.2.0 or issues a workflow command or something else?

**Comment by aaron-steinfeld** [comment]
> @aaron-steinfeld so https://app.circleci.com/pipelines/github/hypertrace/helm-gcs-packager I think we should release 0.2.0 and this is good practice anyway. What's the process to do that? Do we push a git tag 0.2.0 or issues a workflow command or something else?

In the current release policy, the version change would be based on the (semantic) commit messages included in a merge: https://github.com/hypertrace/hypertrace-gradle-version-settings-plugin#default-versioning-rules . So a minor version bump would indicate a feature, and be created by a commit message including `feat: <message>`. By default, we'd get a patch version.

In terms of the goals of this issue, there's two things that need to change for each repository.
1. Updating the docker plugin version - this will start producing the branch tag in addition to any release tags
2. Updating the circleci config to:
   1. Stop tagging and publishing on every commit to main
   2. Add a workflow triggered by a tag of the form `release-x.y.z` that starts the release process, including removing `releasse-x.y.z` as a tag, adding `x.y.z` and publishing any artifacts using the `x.y.z` tag (as well as `latest` for docker images)

Once those changes are done, the versions would be manually controlled and trigger by pushing a git tag of the form `release-0.2.0`

**Comment by adriancole** [comment]
note: this diff is needed for build images (ex just packaging 3rd party like kafka). I'm not sure what else is needed for things that use code, but until the gradle plugin is up to date and this is in, automatic versions still apply on every commit!

https://github.com/hypertrace/kafka/pull/10

**Comment by adriancole** [comment]
a variant of https://github.com/hypertrace/pinot/pull/19 may need to be applied to kafka, helm-gcs-packager and schema-registry cc @aaron-steinfeld @ravisingal before we continue applying these forward

**Comment by adriancole** [comment]
also we need to sweep for latest helm-packager plugin 0.3.0 at the moment https://github.com/hypertrace/pinot/pull/22

**Comment by aaron-steinfeld** [comment]
> a variant of [hypertrace/pinot#19](https://github.com/hypertrace/pinot/pull/19) may need to be applied to kafka, helm-gcs-packager and schema-registry cc @aaron-steinfeld @ravisingal before we continue applying these forward

Yep. Worked with @ravisingal to get that working for pinot today. Because there are multiple artifact types requiring different build containers, we hold off to do the tag manipulation until the last build. That took a bit of back and forth today, but we've updated the helm publish image (0.3.0 as you mentioned above) to support that now, so the pinot pattern should be good to roll forward for repos with a helm artifact.

**Comment by adriancole** [comment]
^^ thx I'll give it a go!

**Comment by JBAhire** [comment]
We addressed this while moving to GitHub actions based CI (https://github.com/hypertrace/hypertrace/issues/144). This has been applied across all repositories now.
