### ISSUE TITLE
[use-case] provide a way to create kubernetes manifeststs for deployment

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#196]
## Use Case
Adding support for vanilla kubernetes installation (without helm). Some of the users of Hypertrace have reported that they are using kubernetes manifests for deployment and management of Hypertrace instead of helm which we provide out of the box. 

Adding support to generate manifests will simplify those kinda deployments as well.

## Proposal
Adding one more option in `hypertrace.sh` script like `generate-artifacts` which will generate kubernetes manifests as per requirements with additional options like
- option to generate kubernetes manifests for individual service
- option to generate kubernetes manifests for pre-install and post-install tasks

**Comment by kotharironak** [comment]
we can do,
`hypetrace.sh --dry-run` : generate all manifests for both data + platform services
`hypetrace.sh --dry-run --pre-install-tasks` : generate manifests for containing all pre-install hooks and its config-maps
`hypetrace.sh --dry-run --post-install-tasks` : generate manifests for containing all post-install hooks and its config-maps
`hypetrace.sh --dry-run --service <service_name>` : generate manifest for specific service including its pre/post install hook for verification.

**Comment by kotharironak** [comment]
Final commands are ,
```
./hypertrace.sh generate-manifests
./hypertrace.sh generate-manifests --service <service-name>
./hypertrace.sh generate-manifests --deps pre-install-tasks
./hypertrace.sh generate-manifests --deps post-install-tasks
```
