### ISSUE TITLE
RawSpansGrouper Optimisation 

### ISSUE THREAD

**Issue by rish691** [hypertrace/hypertrace#228]
Problem:
The current processing which modifies the existing record and puts in the rocksdb is 
not a very optimal way to persists records in Rocksdb. It causes multiple rocksdb level operation to re-trigger 
and in turn causes poor get/put latencies. Also there is an added serde cost.
https://github.com/hypertrace/hypertrace-ingester/blob/main/raw-spans-grouper/raw-[…]ypertrace/core/rawspansgrouper/RawSpansGroupingTransformer.java

As a solution, we can just append the incoming record in a store as byte, without even the need to deserialize it
Reference to the traceId can be used at punctuate time to fetch all the records, stitch it into StructuredTrace and forward it
SessionStore can also be explored

**Comment by rish691** [comment]
https://github.com/hypertrace/hypertrace-ingester/pull/164

**Comment by JBAhire** [comment]
@rish691 , can you please add current state of Raw Span Grouper optimization and close this?

**Comment by rish691** [comment]
This is completed
