### ISSUE TITLE
Bug: Metrics on backend view show that error percentage as 100% 

### ISSUE THREAD

**Issue by subintp** [hypertrace/hypertrace#232]
Problem:
Metrics on backend view show that error_percentage is 100% even though that is clearly not the case from traces.

Screenshot:
Here both errors count and calls count are same
<img width="881" alt="Screenshot 2021-04-08 at 4 42 09 PM" src="https://user-images.githubusercontent.com/1742357/114017208-5e99a080-9889-11eb-91b8-5bc5ca69dedc.png">

<img width="749" alt="Screenshot 2021-04-08 at 12 51 54 PM" src="https://user-images.githubusercontent.com/1742357/114017498-b6380c00-9889-11eb-9f19-1985237d79fa.png">

**Comment by kotharironak** [comment]
This is happening as we are only checking the existence of `error` attributes. However, as per [open tracing semantics](https://github.com/opentracing/specification/blob/master/semantic_conventions.md), span error is represented as boolean. 
<img width="1498" alt="Screenshot 2021-04-08 at 9 06 47 PM" src="https://user-images.githubusercontent.com/53209990/114055408-60298f80-98ae-11eb-9c4f-7800de7d2803.png">

As per open telemetry, the span level error is indicated using `status.code` as `unset`, `ok`, and error - https://github.com/open-telemetry/opentelemetry-specification/blob/ae31114e2d441f1ecd249ce11bb924a6ac54b5d6/specification/trace/api.md#set-status

**Comment by JBAhire** [comment]
This has been resolved with https://github.com/hypertrace/hypertrace-ingester/pull/169 and fix is available in latest release.
