### ISSUE TITLE
Bug: External HTTP backends are not showing as backend after upgrading from 0.1.7 to 0.1.10

### ISSUE THREAD

**Issue by subintp** [hypertrace/hypertrace#235]
Problem:
External HTTP backend calls are showing as unknown backends on 0.1.10. 
Same trace is showing correct backend on 0.1.7.

**Comment by JBAhire** [comment]
This has been resolved with PR: https://github.com/hypertrace/hypertrace-ingester/pull/173 and available after release v0.2.0
