### ISSUE TITLE
Service page view is not working with latest 0.2.0 release with Postgres as document store

### ISSUE THREAD

**Issue by kotharironak** [hypertrace/hypertrace#248]
As part of the release - https://github.com/hypertrace/hypertrace/releases/tag/0.2.0, we have observed that when it is deployed with Postgres, we are seeing errors on the `Service` page view and `API Endpoint` view page. As an example, whenever we click on any service, it shows a page with an error `Take me home` button.

<img width="1674" alt="service-list" src="https://user-images.githubusercontent.com/53209990/120426726-45473900-c38e-11eb-8532-6f48a833a0c6.png">
<img width="1671" alt="take-me-home" src="https://user-images.githubusercontent.com/53209990/120426730-4710fc80-c38e-11eb-9e86-e5de820ae90e.png">

**Comment by JBAhire** [comment]
This is resolved with the document store PR: https://github.com/hypertrace/document-store/pull/52 . @kotharironak , can you please add RCA for this?

Closing this as it has been resolved with[ release v0.2.1](https://github.com/hypertrace/hypertrace/releases/tag/0.2.1) .
