### ISSUE TITLE
I don't know where else to report it but your site is unreadable

### ISSUE THREAD

**Issue by luolong** [hypertrace/hypertrace#29]
I was trying to get more info on hypertrace project and it seems to be completely broken.

Basically this is what I am seeing:
![pilt](https://user-images.githubusercontent.com/133101/91321280-1f6d8200-e7c7-11ea-91f0-fc2e546f277c.png)

**Comment by dnielsen** [comment]
@luolong We were unaware of this problem, so thank you for reporting it. It appears from your screenshot that the images were not loading. It's hard to tell why. Perhaps our host or marketo had a problem. But they appear to be loading no. I have tested hypertrace.org in 3 major browsers (Firefox, Chrome, Safari) on desktop and mobile (6 total). Here are 3. Can you confirm it is working for you now?
<img width="1791" alt="Screen Shot 2020-08-26 at 9 24 17 AM" src="https://user-images.githubusercontent.com/392292/91332639-5d47b780-e781-11ea-8af8-93d98618b93e.png">

**Comment by luolong** [comment]
Yes, it seems to be fine now.

**Comment by jcchavezs** [comment]
I wonder what would be the ideal channel for future similar issues.

tor. 27. aug. 2020, 11:01 skrev Roland Tepp <notifications@github.com>:

**Comment by dnielsen** [comment]
The best place for feedback about the website is Slack https://hypertrace.slack.com
