### ISSUE TITLE
Switch to docker-compose v3 (currently on v2.4)

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#35]
Currently we are using docker-compose v2.4 to be able to access some of the features which are removed in v3. Especially things like conditional dependency (in v2.4 you can add condition for all other services your service depends on.) are very helpful considering we are dealing with considerably large stack here. 

Once we have some reliability and stability issues resolved let's plan to switch to v3.

**Comment by adriancole** [comment]
my 2p is this is super low priority as we aren't missing anything, and the barriers help with reliability. We can defer work until a user asks for something specific in 3.

**Comment by jcchavezs** [comment]
I'd close for now as this isn't a priority but let anyone feel free to reopen.
