### ISSUE TITLE
Simplify the config bootstrapping process by removing additional job for config-bootstrapper

### ISSUE THREAD

**Issue by buchi-busireddy** [hypertrace/hypertrace#36]
Hypertrace needs two kinds of configuration to be present for the entities and query layer to work. 
* entity types configuration --> owned by Entity Service
* attribute metadata --> owned by Attribute Service

Currently, config-bootstrapper uses the clients of attribute-service and entity-service to initialize the configuration. In single node setup, this is introducing dependencies b/w bootstrapper and services, there by either delaying the setup startup or makes it fragile.

Here are some ways in which we can fix it:
`1` Let the clients of ES and AS retry with timeout so that we can reduce the fragility. Simple approach, just needs the gRPC client retry tuning.
`2` Fold the config-bootstrapper into hypertrace-federated-service with git submodules. Though this is a quick job, let it be done. The order in which services are started in federated-service should take care of fragility. This also avoids an extra pod in the startup.
`3` Convert config-bootstrapper into a library and fold into corresponding services. Attribute initialization will be done in attribute-service after the service comes up, similarly entity types.
`4` ??

IMO, `1` should take care of the fragility and simple to fix.

cc @kotharironak @adriancole

**Comment by kotharironak** [comment]
Yes,  I was about to incorporate option (1) as an immediate fix. But, (2) also seems promising and can help in the reduction of startup jobs. 

In my opinion, converting bootstrapper as a library of an option (3), we should do irrespective of whether it can be used in the corresponding service (attribute, federated, entity) or via startup job.
- job vs part of service: both have pros and cons. So, if services are not having in other heavy init tasks, it should be fine to be part of it as on failure we have to restart service. For now, attribute and entity service are not heavy on init, so we can use as suggested in option (3) as well.  

Let me know if you have any specific reasoning between (1) or (2) as an immediate fix.

**Comment by kotharironak** [comment]
As part of an immediate fix,  we will go with as below, in federated, 

1. start grpc server and timer thread for delaying jetty server registration 
2. timer thread will wait for bootstrapper to finish by using entity service client to check if DB has data for configured time and retry 
3. after retry/timeout, start a jetty server for UI  with a log message if (2) success, show log message all UP else show log message config-bootstrapper could have failed, re-run that job.

As a long term fix, we will explore option (3) where we will convert config-bootstrapper as a library which could be used in respective service during start-up or it can be used directly into the backing image.

**Comment by kotharironak** [comment]
The PR - https://github.com/hypertrace/hypertrace-federated-service/pull/19/ - provides proposed immediate fix.

**Comment by kotharironak** [comment]
I am closing this, pl, re-open if needed.
