### ISSUE TITLE
 Setup docker CI for helm setup in Hypertrace repo.

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#68]
We have a working CI setup for `docker-compose` setup now. Can we setup CI for `helm-setup` as well?

### Why do we need it?
As lot of changes have happened recently and some of those can break helm setup once we update charts there. Having CI will help us detecting those issues before merging PRs related to Kubernetes/helm setup.

**Comment by jcchavezs** [comment]
wanna take a stab on this @JBAhire?

**Comment by pavolloffay** [comment]
I can take a look at this one.

**Comment by adriancole** [comment]
@pavolloffay awesome. ping back here with any news

**Comment by JBAhire** [comment]
I have addressed this with GitHub action CI (https://github.com/hypertrace/hypertrace/pull/189) which works something like this (https://github.com/hypertrace/hypertrace/runs/1734041658?check_suite_focus=true).
