### ISSUE TITLE
URLs to access few pages in UI are broken

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#71]
In docker-compose setup we are using UI in hypertrace-service which is using Jetty server. Some of the URLs in this deployment are broken. List of broken URLs is as follows:

#### 1. Services
- Go to Home -> Services -> Select any service -> Refresh the service home page

<img width="1790" alt="Screenshot 2020-09-28 at 2 24 58 PM" src="https://user-images.githubusercontent.com/26570044/94411616-6835a380-0196-11eb-9701-0fbeba764c1d.png">

#### 2. Traces
- Go to Home -> Services -> Select any service -> Go to traces tab -> Refresh the page
<img width="1790" alt="Screenshot 2020-09-28 at 2 26 14 PM" src="https://user-images.githubusercontent.com/26570044/94411768-94512480-0196-11eb-9f3f-265563f0b95f.png">

#### 3. Trace View
- Go to Home -> Services -> Select any service -> Go to traces tab-> Select any trace to see trace view -> Refresh the page

<img width="1790" alt="Screenshot 2020-09-28 at 2 14 40 PM" src="https://user-images.githubusercontent.com/26570044/94411417-2c024300-0196-11eb-9484-aa6f30f9d6d1.png">

#### 4. Backends
- Go to Home -> Backends -> Select any backend -> Refresh the backend home page

<img width="1790" alt="Screenshot 2020-09-28 at 2 28 01 PM" src="https://user-images.githubusercontent.com/26570044/94411950-d37f7580-0196-11eb-9388-66d021b0f090.png">

#### 5. Filter by criteria in both backends and services Traces tab

<img width="1790" alt="Screenshot 2020-09-28 at 2 29 26 PM" src="https://user-images.githubusercontent.com/26570044/94412100-0590d780-0197-11eb-9a88-7ed95320121b.png">

#### 5. Endpoints
- Click any endpoint from home page and refresh endpoint dashboard. 
<img width="1286" alt="Screenshot 2020-10-01 at 9 47 59 AM" src="https://user-images.githubusercontent.com/26570044/94767866-5d178900-03cb-11eb-8687-ad7021bb337e.png">

**Comment by jcchavezs** [comment]
Wanna add this check to CI too?

**Comment by JBAhire** [comment]
sure, @jcchavezs

**Comment by kotharironak** [comment]
PR - https://github.com/hypertrace/hypertrace-service/pull/36 - closes this issue.
