### ISSUE TITLE
Setup Windows CI for docker-compose setup

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#87]
## Use Case
Windows CI for docker-compose will make sure any change is not breaking docker-compose setup on windows. 

## Proposal
We can use GitHub actions/CircleCI to build windows CI wish will trigger on every pull request so we can verify successful install on windows.

**Comment by JBAhire** [comment]
_Distro: Windows Server 2019_

- We tried creating CI for windows using CircleCI as well as GitHub actions and it wasn’t able to run because it doesn’t support Linux Containers. While doing research (google search) around this I came across few articles which mentioned that Hyper-v as primary requirement to run linux containers on windows which completely makes sense.

- After reading this (https://sebastiangogola.com/lcow-linux-containers-on-windows/) article and trying out things on windows server, we were pretty sure about the virtualisation issues(especially nested virtualisation with hyper-v) in case we are doing it in CI.

- And this bought us to conclusion that GitHub action doesn’t support Linux container on Windows Server 2016/2019, because the main requirement is Docker Desktop Enterprise. Out of the box, Docker on Windows only run Windows container. To use Linux containers on Windows Server , you need to use the Docker Desktop Enterprise which includes a full LinuxKit system for running [Docker Linux containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10-linux). Another drawback is that they can not pre-install Docker Desktop Enterprise due to license policy agreement.

As per the issue here:   actions/virtual-environments#1143 

- So, as long as this issues is somehow addressed by Microsoft or docker we are not sure if we can do this.

**Comment by jcchavezs** [comment]
We still would like to hear from people willing as a user reference.
