### ISSUE TITLE
Error while removing network

### ISSUE THREAD

**Issue by mertingen** [hypertrace/hypertrace#88]
When I run the following command, I get an error while removing the network. The rest of them are successful.

OS: Ubuntu 16.04

> docker-compose -f docker-compose.yml down

![22](https://user-images.githubusercontent.com/15813184/95310275-e5e36880-0894-11eb-97bc-55fafdd5887d.png)

**Comment by jcchavezs** [comment]
Hi @mertingen, thanks for coming by! This is a docker-compose question more than hypertrace, it feels like you tried an earlier version of the docker-compose file and now there are orphan containers. I am closing this issue as this is not related to HT.

**Comment by mertingen** [comment]
Hi @jcchavezs ,

I was wondering I pulled the latest repository yesterday. Might it be possible an older docker-compose.yml file.
Additionally, I stopped the running containers by "CTRL-V" and after that I run "down" command.

**Comment by kotharironak** [comment]
Yes. If there is a change in name (service or container name) in the docker-compose file, and if you have run the docker-compose with a prior name while doing `CTRL-V` and `down`,  will give you a message for orphan containers. In such cases, you can clean those orphan containers using the below command,
`docker-compose -f docker-compose.yml down --remove-orphans`
